#!/usr/bin/python3
import sys
import os
import getopt
import cosihaveto as ch
#from cosihaveto.weighted_random import weighted_random_by_dict

help = '''
Help message can go here
'''

def usage():
        print(help)


def run_getopts():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "l:psmh",
                                   ["length", "prefix", "suffix",
                                    "medical", "help"])
    except getopt.GetoptError as err:
        print(err)
        usage()
        sys.exit(2)
    word_length = 10
    prefix = False
    suffix = False
    medical = False

    for o, a in opts:
        if o in ('-h', '--help'):
            usage()
            sys.exit()
        elif o in ('-l', '--length'):
            word_length = a
            if word_length.isnumeric():
                word_length = int(word_length)
        elif o in ('-p', '--prefix'):
            prefix = True
        elif o in ('-s', '--suffix'):
            suffix = True
        elif o in ('-m', '--medical'):
            medical = True
        else:
            assert False, "unhandled option"
    return word_length, prefix, suffix, medical

if __name__ == '__main__':
    script_path = os.path.dirname(os.path.abspath(__file__))
    word_length, prefix, suffix, medical = run_getopts()
    valid_sounds = ch.load_file(f"{script_path}/data/passwordinputs.json")
    letter_frequencies = ch.load_file(f"{script_path}/data/letter_frequencies_3.json")
    suggested_word = ch.build_word("", word_length, valid_sounds, letter_frequencies, prefix, suffix, medical)
    print(suggested_word)
